# The URL the site will be built for
base_url = "https://systemprogrammerwizzard.github.io/portfolio"
title = "System Programming Hub"



# Whether to automatically compile all Sass files in the sass directory
compile_sass = false

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

# The theme supports feeds (RSS and ATOM)
generate_feeds = true

# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
feed_filenames = ["rss.xml", "atom.xml"]

# Optional: enable tags
taxonomies = [
    {name = "tags"}
]

# Code highlighting
[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]
# One of: blue, green, orange, pink, red.
# Defaults to blue.
# Append -light for light themes, e.g. blue-light
# Or append -auto, e.g. blue-auto
accent_color = "green"

# One of: blue, dark, green, orange, pink, red, light, auto
# Enabling dark background will also modify primary font color to be darker.
# Defaults to accent color (or, if not accent color specified, to blue).
background_color = "dark"

# The logo text - defaults to "Terminimal theme"
logo_text = "System Programming"

# The logo link - defaults to base_url.
logo_home_link = "/"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "System Programming Hub"

# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration
    {name = "home", url = "$BASE_URL"},
    {name = "blog", url = "$BASE_URL/blog"},
#    {name = "courses", url = "$BASE_URL/courses"},
    # {name = "projects", url = "$BASE_URL/projects"},  # Temporarily hidden
    {name = "about", url = "$BASE_URL/about"},
    {name = "contact", url = "$BASE_URL/contact"},

    # set newtab to true to make the link open in new tab
    {name = "github", url = "https://github.com", newtab = true},
]

# Whether to show links to earlier and later (aka. higher/lower) posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Thanks for reading! Read other posts?"

# Use full Hack character set, not just a subset.
# Switch this to true if you need full unicode support.
# Defaults to false.
use_full_hack_font = false

# Optional: Set how <title> elements are rendered.
page_titles = "combined"